sonar.projectKey=Folios
sonar.projectName=Folios
sonar.projectVersion=0.1.4

sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.rust.lcov.reportPaths=target/sonar/lcov.info

sonar.exclusions=\
  target/**,\
  _build/**,\
  build/**,\
  build-dir/**,\
  builddir/**,\
  .build/**,\
  .flatpak/**,\
  .flatpak-builder/**,\
  .gnome-builder/**,\
  subprojects/blueprint-compiler/**,\
  subprojects/.wraplock,\
  src/config.rs,\
  **/*.gresource,\
  **/*.ui~,\
  **/*.css~,\
  **/*~
