sonar.projectKey=fvtronics_quire
sonar.organization=fvtronics
sonar.projectName=Quire
sonar.projectVersion=0.2.4

sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.rust.lcov.reportPaths=target/sonar/lcov.info
sonar.rust.clippy.enabled=false
sonar.rust.clippyReport.reportPaths=target/sonar/clippy.json

sonar.exclusions=\
  target/**,\
  _build/**,\
  build/**,\
  build-dir/**,\
  builddir/**,\
  .build/**,\
  .flatpak/**,\
  .flatpak-builder/**,\
  .gnome-builder/**,\
  subprojects/blueprint-compiler/**,\
  subprojects/.wraplock,\
  src/config.rs,\
  **/*.gresource,\
  **/*.ui~,\
  **/*.css~,\
  **/*~

sonar.coverage.exclusions=\
  src/application.rs,\
  src/main.rs,\
  src/window.rs,\
  src/window/compress.rs,\
  src/window/extract.rs,\
  src/window/merge.rs,\
  src/window/organize.rs,\
  src/window/split.rs,\
  src/window/metadata.rs,\
  src/window/ui.rs,\
  src/window/workspace.rs
