name: Folios Pipeline

on:
  push:
    branches: ["master"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    name: Checks
    runs-on: linux-amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          if command -v sudo >/dev/null; then
            SUDO=sudo
          else
            SUDO=
          fi

          $SUDO apt-get update
          $SUDO apt-get install -y --no-install-recommends \
            appstream \
            blueprint-compiler \
            desktop-file-utils \
            gettext \
            libglib2.0-bin \
            libadwaita-1-dev \
            libgtk-4-dev \
            libpoppler-glib-dev \
            meson \
            pkg-config

      - name: Install Rust
        uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Generate Build Configuration
        run: meson setup builddir

      - name: Format Check
        run: cargo fmt --all -- --check

      - name: Whitespace Check
        run: git diff --check

      - name: Clippy
        run: cargo clippy --locked --all-targets -- -D warnings

      - name: Test
        run: cargo test --locked
